### ISSUE TITLE
Use github actions to auto-compile a windows binary for the comparison tool

### ISSUE THREAD

**Issue by MichaMans** [ibpsa/project1-destest#5]
With github actions it should be possible to auto-compile a standalone windows binary for the comparison tool. I'll have a deeper look into it.

**Comment by mwetter** [comment]
@MichaMans : Keep in mind that github actions has only a limited number of free minutes, otherwise one has to pay. We set up payment on travis, but not on github actions as we rather want to keep the funds to sponsor student scholarships. Also, travis has the advantage that the monthly payment is fixed, whereas with github actions it is variable, or you may run out of minutes in which case the service stops for the rest of the month. This is why for the IBPSA Modelica Library, we will use github actions only for syntax check which is very fast compared, and keep the time intensive tasks on travis.

**Comment by MichaMans** [comment]
@mwetter thanks for pointing that out. I honestly wasn't aware of that as I understood the phrase: "2,000 minutes/month;free for public repositories" that it is free for public repositories. But if not we can think about testing it with 2,000 minutes (which might be shared for modelica-ibpsa, ibpsa-project1, and project1-destest) and there we need to first analyse what amount we have left for "project1-destest". Another option is to use your paid travis subscription. I'll have a look in to that how they can provide job artifact (compiled binaries) for the repo.

**Comment by mwetter** [comment]
@MichaMans : I think you are right that it is free for public repos (https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions), at least for now. (Travis also used to be free until they changed in November.)

**Comment by MichaMans** [comment]
@mwetter Thanks for clarifying, maybe I can try to integrate that with actions and if they change it, we can consider moving to Travis again. (I hope it will stay free as it is 1. Microsoft / 2. They moved from paid plans to free plans (so other way around again makes no sense) / 3. Good and almost no cost for infrastructure in comparison to Travis (of course thats what I am assuming, time will tell 😃 )

**Comment by mwetter** [comment]
@MichaMans : Yes, please integrate it with github actions
